name: Terraform Dry Run

on:
  push:
  workflow_dispatch:
    inputs:
      create_instance:
        description: 'Set to "true" to create the EC2 instance, "false" to destroy it'
        required: false
        default: 'true'
      create_access_key:
        description: 'Set to "true" to create access keys for the IAM user'
        required: false
        default: 'false'

jobs:
  terraform:
    name: Terraform Plan --dry-run
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/sandbox

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Generate Backend Config
        run: |
          echo 'bucket         = "${{ vars.AWS_S3_TF }}"' > backend-config.hcl
          echo 'key            = "${{ secrets.S3_PATH_TO_TF_STATE }}"' >> backend-config.hcl
          echo 'region         = "us-west-1"' >> backend-config.hcl
          echo 'dynamodb_table = "${{ secrets.AWS_DYNAMODB_TABLE_TF }}"' >> backend-config.hcl
          echo 'encrypt        = true' >> backend-config.hcl
    
      - name: Generate Sensitive Variables File
        run: |
          echo 's3_bucket_configs = {' > sensitive.tfvars
          echo '  "s3_bucket_1" = {' >> sensitive.tfvars
          echo '    bucket_name       = "${{ secrets.S3_BUCKET_NAME_1 }}"' >> sensitive.tfvars
          echo '    acl               = "private"' >> sensitive.tfvars
          echo '    enable_versioning = false' >> sensitive.tfvars
          echo '    tags              = { Project = "ProjectA" }' >> sensitive.tfvars
          echo '  }' >> sensitive.tfvars
          echo '  "s3_bucket_2" = {' >> sensitive.tfvars
          echo '    bucket_name       = "${{ secrets.S3_BUCKET_NAME_2 }}"' >> sensitive.tfvars
          echo '    acl               = "private"' >> sensitive.tfvars
          echo '    enable_versioning = false' >> sensitive.tfvars
          echo '    tags              = { Project = "ProjectB" }' >> sensitive.tfvars
          echo '  }' >> sensitive.tfvars
          echo '}' >> sensitive.tfvars
    
      - name: Terraform Init
        run: terraform init -backend-config=backend-config.hcl
  
      - name: Terraform Apply
        run: terraform plan -var-file="sensitive.tfvars" -auto-approve
  
      - name: Clean Up
        if: always()
        run: |
          rm -f backend-config.hcl
          rm -f sensitive.tfvars

      - name: Output IAM Access Key (Sensitive)
        if: ${{ github.event.inputs.create_access_key == 'true' }}
        run: |
          terraform output -json iam_access_key_id > access_key.json
          terraform output -json iam_secret_access_key > secret_key.json
        env:
          TF_IN_AUTOMATION: true  # Suppress sensitive output

      # Handle sensitive outputs securely, e.g., store in GitHub Actions secrets or external vaults
